LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE    := I7565H1H2
LOCAL_SRC_FILES := $(TARGET_ARCH_ABI)/libI7565H1H2.a
include $(PREBUILT_STATIC_LIBRARY)


include $(CLEAR_VARS)

LOCAL_MODULE := MyLibrary
LOCAL_SRC_FILES := MyLibrary.c
LOCAL_STATIC_LIBRARIES += I7565H1H2
include $(BUILD_SHARED_LIBRARY)